apiVersion: agent.atomix.io/v1alpha1
kind: AtomixCluster
metadata:
  name: example-atomixcluster
spec:
  version: 3.1.0
  managementGroup:
    size: 1
    storage:
      className: fast-disks
  partitionGroups:
    - name: raft
      size: 10
      partitions: 10
      env:
        - name: JAVA_OPTS
          value: -Xmx2G
      resources:
        requests:
          memory: 2Gi
      raft:
        storage:
          className: fast-disks