apiVersion: agent.atomix.io/v1alpha1
kind: AtomixBenchmark
metadata:
  name: example-benchmark
spec:
  cluster: example-atomixcluster
  version: latest
  workers: 3
  env:
    - name: JAVA_OPTS
      value: -Xmx1G
  resources:
    requests:
      memory: 1Gi