apiVersion: agent.atomix.io/v1alpha1
kind: AtomixCluster
metadata:
  name: example-atomixcluster
spec:
  version: latest
  managementGroup:
    size: 1
    storage:
      className: fast-disks
  partitionGroups:
    - name: raft
      size: 3
      partitions: 3
      env:
        - name: JAVA_OPTS
          value: -Xmx2G
      resources:
        requests:
          memory: 2Gi
          cpu: .5
      raft:
        storage:
          className: fast-disks
  chaos:
    monkeys:
      - name: crash
        crash:
          rateSeconds: 60
      - name: partition-bridge
        partition:
          partitionStrategy:
            type: Bridge
          rateSeconds: 600
      - name: partition-isolate
        partition:
          partitionStrategy:
            type: Isolate
          rateSeconds: 300
          periodSeconds: 300