apiVersion: agent.atomix.io/v1alpha1
kind: AtomixCluster
metadata:
  name: example-atomixcluster
spec:
  version: latest
  managementGroup:
    size: 1
    storage:
      className: fast-disks
  partitionGroups:
    - name: raft
      size: 5
      partitions: 5
      env:
        - name: JAVA_OPTS
          value: -Xmx2G
      resources:
        requests:
          memory: 2Gi
          cpu: .5
      raft:
        storage:
          className: fast-disks