// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtomixCluster) DeepCopyInto(out *AtomixCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtomixCluster.
func (in *AtomixCluster) DeepCopy() *AtomixCluster {
	if in == nil {
		return nil
	}
	out := new(AtomixCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AtomixCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtomixClusterList) DeepCopyInto(out *AtomixClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AtomixCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtomixClusterList.
func (in *AtomixClusterList) DeepCopy() *AtomixClusterList {
	if in == nil {
		return nil
	}
	out := new(AtomixClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AtomixClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Benchmark) DeepCopyInto(out *Benchmark) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Benchmark.
func (in *Benchmark) DeepCopy() *Benchmark {
	if in == nil {
		return nil
	}
	out := new(Benchmark)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	in.ManagementGroup.DeepCopyInto(&out.ManagementGroup)
	if in.PartitionGroups != nil {
		in, out := &in.PartitionGroups, &out.PartitionGroups
		*out = make([]PartitionGroupSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Benchmark != nil {
		in, out := &in.Benchmark, &out.Benchmark
		*out = new(Benchmark)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Compaction) DeepCopyInto(out *Compaction) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Compaction.
func (in *Compaction) DeepCopy() *Compaction {
	if in == nil {
		return nil
	}
	out := new(Compaction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogPartitionGroup) DeepCopyInto(out *LogPartitionGroup) {
	*out = *in
	in.PersistentPartitionGroup.DeepCopyInto(&out.PersistentPartitionGroup)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogPartitionGroup.
func (in *LogPartitionGroup) DeepCopy() *LogPartitionGroup {
	if in == nil {
		return nil
	}
	out := new(LogPartitionGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementGroup) DeepCopyInto(out *ManagementGroup) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Storage.DeepCopyInto(&out.Storage)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementGroup.
func (in *ManagementGroup) DeepCopy() *ManagementGroup {
	if in == nil {
		return nil
	}
	out := new(ManagementGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitionGroup) DeepCopyInto(out *PartitionGroup) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitionGroup.
func (in *PartitionGroup) DeepCopy() *PartitionGroup {
	if in == nil {
		return nil
	}
	out := new(PartitionGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PartitionGroupSpec) DeepCopyInto(out *PartitionGroupSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Raft != nil {
		in, out := &in.Raft, &out.Raft
		*out = new(RaftPartitionGroup)
		(*in).DeepCopyInto(*out)
	}
	if in.PrimaryBackup != nil {
		in, out := &in.PrimaryBackup, &out.PrimaryBackup
		*out = new(PrimaryBackupPartitionGroup)
		**out = **in
	}
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = new(LogPartitionGroup)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PartitionGroupSpec.
func (in *PartitionGroupSpec) DeepCopy() *PartitionGroupSpec {
	if in == nil {
		return nil
	}
	out := new(PartitionGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentPartitionGroup) DeepCopyInto(out *PersistentPartitionGroup) {
	*out = *in
	out.PartitionGroup = in.PartitionGroup
	in.Storage.DeepCopyInto(&out.Storage)
	out.Compaction = in.Compaction
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentPartitionGroup.
func (in *PersistentPartitionGroup) DeepCopy() *PersistentPartitionGroup {
	if in == nil {
		return nil
	}
	out := new(PersistentPartitionGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrimaryBackupPartitionGroup) DeepCopyInto(out *PrimaryBackupPartitionGroup) {
	*out = *in
	out.PartitionGroup = in.PartitionGroup
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrimaryBackupPartitionGroup.
func (in *PrimaryBackupPartitionGroup) DeepCopy() *PrimaryBackupPartitionGroup {
	if in == nil {
		return nil
	}
	out := new(PrimaryBackupPartitionGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RaftPartitionGroup) DeepCopyInto(out *RaftPartitionGroup) {
	*out = *in
	in.PersistentPartitionGroup.DeepCopyInto(&out.PersistentPartitionGroup)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RaftPartitionGroup.
func (in *RaftPartitionGroup) DeepCopy() *RaftPartitionGroup {
	if in == nil {
		return nil
	}
	out := new(RaftPartitionGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}
